# Generated by Django 3.0.8 on 2020-08-13 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(default='')),
                ('tones', models.TextField(default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_analysis_app.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_extension', models.CharField(max_length=50)),
                ('company_description', models.TextField(default='')),
                ('employees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('description_func', models.TextField(default='')),
                ('description_non_func', models.TextField(default='')),
                ('keywords_func', models.TextField(default='')),
                ('keywords_non_func', models.TextField(default='')),
                ('concepts', models.TextField(default='')),
                ('categories', models.TextField(default='')),
                ('applicants', models.ManyToManyField(related_name='applicants', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('current_employees', models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='resume_analysis_app.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default='resumes/_.pdf', upload_to='resumes')),
                ('filename', models.CharField(default='my_resume.pdf', max_length=50)),
                ('resume_plain_text', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('concepts', models.TextField(default='')),
                ('categories', models.TextField(default='')),
                ('personality', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
