# Generated by Django 3.0.8 on 2020-08-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0002_auto_20200813_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='resume_analysis_app.JobDescription'),
        ),
    ]
