# Generated by Django 3.0.8 on 2020-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0002_auto_20200731_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
