# Generated by Django 3.0.8 on 2020-08-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0003_account_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='resume_analysis_app.JobDescription'),
        ),
    ]
