# Generated by Django 3.0.8 on 2020-08-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0004_auto_20200813_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_org', to='resume_analysis_app.Organisation'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_org', to='resume_analysis_app.Organisation'),
        ),
    ]
