# Generated by Django 3.0.8 on 2020-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0004_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='filename',
            field=models.CharField(default='my_resume.pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='resumes/CV.pdf', upload_to='resumes'),
        ),
    ]
