# Generated by Django 3.0.8 on 2020-08-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0005_auto_20200813_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='resume_analysis_app.JobDescription'),
        ),
        migrations.AlterField(
            model_name='account',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_org', to='resume_analysis_app.Organisation'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_org', to='resume_analysis_app.Organisation'),
        ),
    ]
