# Generated by Django 3.0.8 on 2020-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0006_applicant_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='description',
            new_name='description_func',
        ),
        migrations.RenameField(
            model_name='jobdescription',
            old_name='keywords',
            new_name='keywords_func',
        ),
        migrations.AddField(
            model_name='applicant',
            name='categories',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='concepts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='categories',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='concepts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='description_non_func',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='keywords_non_func',
            field=models.TextField(default=''),
        ),
    ]
