# Generated by Django 3.0.8 on 2020-08-13 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_analysis_app', '0006_auto_20200813_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
