# Generated by Django 3.0.8 on 2020-08-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0007_auto_20200805_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume_plain_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='description_func',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='description_non_func',
            field=models.TextField(default=''),
        ),
    ]
