# Generated by Django 3.0.8 on 2020-08-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0008_auto_20200813_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='keywords_func',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='keywords_non_func',
        ),
    ]
