# Generated by Django 3.0.8 on 2020-08-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0009_auto_20200814_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='categories',
            new_name='category1',
        ),
        migrations.RenameField(
            model_name='jobdescription',
            old_name='categories',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='account',
            name='category2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='category3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='category2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='category3',
            field=models.TextField(default=''),
        ),
    ]
