# Generated by Django 3.0.8 on 2020-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0010_auto_20200814_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='category2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='category3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category3',
            field=models.CharField(max_length=50),
        ),
    ]
