# Generated by Django 3.0.8 on 2020-08-14 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_analysis_app', '0011_auto_20200814_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='recommended',
            field=models.ManyToManyField(blank=True, related_name='recommended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='category1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='category2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='category3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category3',
            field=models.CharField(max_length=100),
        ),
    ]
