# Generated by Django 3.0.8 on 2020-08-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0012_auto_20200814_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='aggregate_personality',
            field=models.TextField(default=''),
        ),
    ]
