# Generated by Django 3.0.8 on 2020-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0014_auto_20200815_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='filename',
            field=models.CharField(default='my_resume.pdf', max_length=50),
        ),
    ]
