# Generated by Django 3.0.8 on 2020-08-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0015_account_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='education',
            field=models.TextField(default=''),
        ),
    ]
