# Generated by Django 3.0.8 on 2020-08-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0016_account_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresponse',
            old_name='tones',
            new_name='language_tones',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='social_tones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='education',
            field=models.TextField(default='[]'),
        ),
    ]
