# Generated by Django 3.0.8 on 2020-08-19 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_analysis_app', '0017_auto_20200815_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='removed',
            field=models.ManyToManyField(blank=True, related_name='removed', to=settings.AUTH_USER_MODEL),
        ),
    ]
