# Generated by Django 3.0.8 on 2020-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0018_jobdescription_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category1',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='category2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='category3',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='concepts',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='account',
            name='keywords',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='account',
            name='personality',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='aggregate_personality',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category1',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category2',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='category3',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='concepts',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='keywords',
            field=models.TextField(default='{}'),
        ),
    ]
