# Generated by Django 3.0.8 on 2020-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0019_auto_20200819_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='personality',
            new_name='pers_agreeabl',
        ),
        migrations.AddField(
            model_name='account',
            name='pers_big5',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='account',
            name='pers_conscien',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='account',
            name='pers_em_range',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='account',
            name='pers_extraver',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='account',
            name='pers_openness',
            field=models.TextField(default='{}'),
        ),
    ]
