# Generated by Django 3.0.8 on 2020-08-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0021_auto_20200819_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='aggregate_personality',
            new_name='aggr_agreeabl',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='aggr_big5',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='aggr_conscien',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='aggr_em_range',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='aggr_extraver',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='aggr_openness',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='needs',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='values',
            field=models.TextField(default='{}'),
        ),
    ]
