# Generated by Django 3.0.8 on 2020-08-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0022_auto_20200820_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job_start',
            field=models.IntegerField(default=2020),
        ),
    ]
