# Generated by Django 3.0.8 on 2020-09-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0024_auto_20200902_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='keywords_req',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.CharField(default='https://www.', max_length=50),
        ),
    ]
