# Generated by Django 3.0.8 on 2020-09-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis_app', '0025_auto_20200902_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='keywords_req',
            field=models.TextField(default='[]'),
        ),
    ]
